<!--suppress JSUnusedLocalSymbols -->
<script type="text/javascript">
    /**
     * Check if coming from PayPal cancellation call, then redirect back to App instead of desktop site
     */
    <?php if ($this->isPaypalCancellation()): ?>
    //<![CDATA[
    function initPipelineCall() {
    }

    var commands = [
        {
            'c': 'broadcastEvent',
            'p': {
                'event': 'closeInAppBrowser',
                'parameters': [{ 'redirectTo': '/cart' }] //todo-konstantin: double check url
            }
        }
    ];

    window.SGAppConnector.sendAppCommands(commands);
    //]]>
    <?php endif; ?>
</script>
