<script type="text/javascript">
    function initPipelineCall() {
        window.SGAppConnector.sendPipelineRequest(
            'login_v1',
            true,
            {'strategy': 'auth_code', 'parameters': {'code': '<?php echo $this->getToken(); ?>'}},
            function (err, serial, output) {
                var commands = [
                    {
                        'c': 'broadcastEvent',
                        'p': {
                            'event': 'userLoggedIn'
                        }
                    }
                ];

                if (<?php echo $this->isShopgateCheckout()
                    ? 'false'
                    : 'true'; ?>) {
                    commands.push(
                        {
                            'c': 'broadcastEvent',
                            'p': {
                                'event': 'closeInAppBrowser',
                                'parameters': [<?php echo $this->getShopgateCallbackData() ?>]
                            }
                        }
                    )
                }

                window.SGAppConnector.sendAppCommands(commands);

                window.location.href = '<?php echo $this->getCheckoutUrl(); ?>';
            }
        )
    }
</script>


