<script type="text/javascript">
  function initPipelineCall () {
    window.SGAppConnector.sendPipelineRequest(
      'shopgate.user.loginUser.v1',
      true,
      {'strategy': 'auth_code', 'parameters': {'code': '<?php echo $this->getToken(); ?>'}},
      function (err, serial, output) {
        var command = {
          'c': 'broadcastEvent',
          'p': {
            'event': 'userLoggedIn'
          }
        }

        window.SGAppConnector.sendAppCommand(command)

        window.location.href = '<?php echo $this->getCheckoutUrl(); ?>'
      }
    )
  }
</script>


